export default {
  GET_SERVICES: Symbol("GET_SERVICES"),
  SELECT_SERVICE: Symbol("SELECT_SERVICE"),


  GET_TABLES: Symbol("GET_TABLES"),
  SELECT_TABLE: Symbol("SELECT_TABLE"),


  GET_PROPERTIES: Symbol("GET_PROPERTIES"),
  RESOLVE_GET_PROPERTIES: Symbol("RESOLVE_GET_PROPERTIES"),

  GET_ROWS: Symbol("GET_ROWS"),
	RESOLVE_GET_DATA: Symbol("RESOLVE_GET_DATA"),
}